Corrections, cosmetics and parameters check

diff --git a/msbuild b/msbuild
--- a/msbuild
+++ b/msbuild
@@ -1,18 +1,18 @@
 #!/bin/bash
 
-export working_dir=$(pwd)
+export VIRTUAL_DEV_WORKING_DIR=$(pwd)
 cd $(dirname $0)
-export vdev_dir="$working_dir/.vdev"
-
 
 source detail/constants
 source detail/utils
 source detail/dictionary
 
 
-if [ ! -d "$vdev_dir" ]
+export VIRTUAL_DEV_WORKSPACE_DIR="$VIRTUAL_DEV_WORKING_DIR/$VIRTUAL_DEV_WORKSPACE_NAME"
+
+if [ ! -d "$VIRTUAL_DEV_WORKSPACE_DIR" ]
 then
-	printf-vdev-error 'current path doesn'"'"'t have any virtual-dev configuration'
+	printf-vdev-error 'current path doesn'"'"'t have any virtual-dev workspace'
 	exit 1
 fi
 
@@ -22,15 +22,15 @@ HELP_MESSAGE=\
     vdev-msbuild [<MSBuild-arguments>...]                (1)
     vdev-msbuild <MVS-version> [<MSBuild-arguments>...]  (2)
 
-Options:
-    <MVS-version>              Specify Visual Studio version explicitly.
+Parameters:
     <MSBuild-arguments>        Arguments for MSBuild.
+    <MVS-version>              Specify Visual Studio version (not year) explicitly.
 
 Notes:
-    Solution or project paths should be relative to project root.
-
-    Form (1) should have .sln or .vcxproj in it'"'"'s arguments.
+    Form (1) should have .sln or .vcxproj file path in it'"'"'s arguments.
     Form (2) does not pass <MVS-version> to MSBuild.
+
+    Solution or project paths should be relative to project root.
 '
 
 
@@ -41,7 +41,34 @@ vs_version=$1
 
 
 #
-# Funtions
+# Functions
+
+validate-parameters()
+{
+	local parameters=("$@")
+
+	array-search-by-pattern '.*\.sln' "${parameters[@]}" > /dev/null
+	if [ $? == 0 ]
+	then
+		return
+	fi
+
+	array-search-by-pattern '.*\.vcxproj' "${parameters[@]}" > /dev/null
+	if [ $? == 0 ]
+	then
+		return
+	fi
+
+	local first_parameter=${parameters[@]}
+	if [[ $first_parameter =~ ^[0-9]+$ ]]
+	then
+		printf '%s\n' "$first_parameter"
+		return
+	fi
+
+	return 1
+}
+
 
 vs-version-for-parameters()
 {
@@ -58,7 +85,7 @@ vs-version-for-parameters()
 	project_path=$(array-search-by-pattern '.*\.vcxproj' "${parameters[@]}")
 	if [ $? == 0 ]
 	then
-		local absolute_solution_path=$(detail/detect-solution-for-project "$project_path")
+		local absolute_solution_path=$(detail/find-solution-for-vcxproj "$project_path")
 	fi
 
 	if [ -z "$absolute_solution_path" ]
@@ -70,7 +97,7 @@ vs-version-for-parameters()
 			return 1
 		fi
 
-		local absolute_solution_path="$working_dir/$solution_path"
+		local absolute_solution_path="$VIRTUAL_DEV_WORKING_DIR/$solution_path"
 	fi
 
 	if [ ! -r "$absolute_solution_path" ]
@@ -102,7 +129,7 @@ msbuild-arguments-from-parameters()
 #
 # Main
 
-vdev_vm_file="$vdev_dir/$VM_FILE"
+vdev_vm_file="$VIRTUAL_DEV_WORKSPACE_DIR/$VM_FILE"
 dictionary-load "$vdev_vm_file" 'vm' 'guest_name'
 
 
@@ -111,6 +138,13 @@ dictionary-load "$vdev_vm_file" 'vm' 'guest_name'
 if [ $# \< 1 ]
 then
 	printf-vdev-error 'too few arguments'
+	printf-message '%s' "$HELP_MESSAGE"
+	exit 1
+fi
+
+if ! validate-parameters "$@"
+then
+	printf-vdev-error 'bad arguments'
 	printf-message '%s' "$HELP_MESSAGE"
 	exit 1
 fi
@@ -134,12 +168,12 @@ fi
 
 # Paths file
 
-vdev_guest_paths_file="$vdev_dir/$GUEST_PATHS_FILE"
+vdev_guest_paths_file="$VIRTUAL_DEV_WORKSPACE_DIR/$GUEST_PATHS_FILE"
 
 detail/check-paths-file "$vdev_guest_paths_file"
 if [ $? == 2 ]
 then
-	printf-vdev-warning 'shared disk on "%s" for this project was changed. This may cause error during compilation. You may need to check paths in the solution.' "$guest_name"
+	printf-vdev-warning 'shared disk on "%s" for this workspace was changed. This may cause error during compilation. You may need to check paths in the solution.' "$guest_name"
 fi
 
 dictionary-load "$vdev_guest_paths_file" 'guest_root_dir' 'guest_msbuild_bat'
@@ -157,7 +191,7 @@ fi
 msbuild_arguments=($(msbuild-arguments-from-parameters "$@"))
 
 # passing arguments through environment variable, because "cmd.exe" will remove "=" character from arguments like "/property:configuration=Release"
-export virtual_dev_arguments="${msbuild_arguments[@]}"
+export VIRTUAL_DEV_ARGUMENTS="${msbuild_arguments[@]}"
 detail/"$vm"/execute "$guest_msbuild_bat" "$guest_root_dir" "$vs_version" | detail/error-format-mvs-to-gcc
 retval=${PIPESTATUS[0]}
 if [ $retval == 1 ]
diff --git a/run-vcxproj b/run-vcxproj
--- a/run-vcxproj
+++ b/run-vcxproj
@@ -1,18 +1,18 @@
 #!/bin/bash
 
-export working_dir=$(pwd)
+export VIRTUAL_DEV_WORKING_DIR=$(pwd)
 cd $(dirname $0)
-export vdev_dir="$working_dir/.vdev"
-
 
 source detail/constants
 source detail/utils
 source detail/dictionary
 
 
-if [ ! -d "$vdev_dir" ]
+export VIRTUAL_DEV_WORKSPACE_DIR="$VIRTUAL_DEV_WORKING_DIR/$VIRTUAL_DEV_WORKSPACE_NAME"
+
+if [ ! -d "$VIRTUAL_DEV_WORKSPACE_DIR" ]
 then
-	printf-vdev-error 'current path doesn'"'"'t have any virtual-dev configuration'
+	printf-vdev-error 'current path doesn'"'"'t have any virtual-dev workspace'
 	exit 1
 fi
 
@@ -23,21 +23,45 @@ HELP_MESSAGE=\
     vdev-run-vcxproj <Path/To/Solution.sln> <Path/To/Project.vcxproj> [<MSBuild-arguments>...]  (2)
     vdev-run-vcxproj <MVS-version> <Path/To/Project.vcxproj> [<MSBuild-arguments>...]           (3)
 
-Options:
+Parameters:
     <Path/To/Project.vcxproj>  Path to .vcxproj file; Visual Studio version will be detected by searching corresponding solution file.
     <Path/To/Solution.sln>     Specify solution file to detect Visual Studio version from it.
     <MVS-version>              Specify Visual Studio version explicitly.
     <MSBuild-arguments>        Arguments for MSBuild.
 
 Notes:
-    "Paths/To/Some.thing" should be relative to project root.
-
     Form (1) passes it'"'"'s first argument to MSBuild.
+
+    "Paths/To/Some.thing" should be relative to project root.
 '
 
 
 #
 # Functions
+
+validate-parameters()
+{
+	local first_parameter=$1
+	local second_parameter=$2
+
+	if [[ $first_parameter =~ .*\.vcxproj ]]
+	then
+		return
+	fi
+
+	if [[ $first_parameter =~ .*\.sln ]] && [[ $second_parameter =~ .*\.vcxproj ]]
+	then
+		return
+	fi
+
+	if [[ $first_parameter =~ ^[0-9]+$ ]] && [[ $second_parameter =~ .*\.vcxproj ]]
+	then
+		return
+	fi
+
+	return 1
+}
+
 
 vs-version-for-parameters()
 {
@@ -51,12 +75,12 @@ vs-version-for-parameters()
 
 	if ! [[ $first_parameter =~ .*\.sln ]]
 	then
-		local solution_path=$(detail/detect-solution-for-project "$first_parameter")
+		local solution_path=$(detail/find-solution-for-vcxproj "$first_parameter")
 	fi
 
 	if [ -z "$solution_path" ]
 	then
-		local solution_path="$working_dir/$first_parameter"
+		local solution_path="$VIRTUAL_DEV_WORKING_DIR/$first_parameter"
 	fi
 
 	if [ ! -r "$solution_path" ]
@@ -132,20 +156,11 @@ find-vcxproj-properties-file()
 }
 
 
-check-vcxproj-properties()
+cache-vcxproj-properties()
 {
 	local vs_version=$1
 	local project_path=$2
-	local properties_dir=$3
-	local msbuild_arguments=("${@:4}")
-
-	local header="$project_path ${msbuild_arguments[@]}"
-	local properties_file_path=$(find-vcxproj-properties-file "$properties_dir" "$header")
-	if [ ! "$working_dir/$project_path" -nt "$properties_file_path" ]
-	then
-		printf '%s\n' "$properties_file_path"
-		return
-	fi
+	local msbuild_arguments=("${@:3}")
 
 	local OutDir
 	OutDir=$(detail/project-property "$vs_version" "$project_path" 'OutDir' "${msbuild_arguments[@]}")
@@ -177,10 +192,29 @@ check-vcxproj-properties()
 }
 
 
+check-vcxproj-properties()
+{
+	local vs_version=$1
+	local project_path=$2
+	local properties_dir=$3
+	local msbuild_arguments=("${@:4}")
+
+	local header="$project_path ${msbuild_arguments[@]}"
+	local properties_file_path=$(find-vcxproj-properties-file "$properties_dir" "$header")
+	if [ ! "$VIRTUAL_DEV_WORKING_DIR/$project_path" -nt "$properties_file_path" ]
+	then
+		printf '%s\n' "$properties_file_path"
+		return
+	fi
+
+	cache-vcxproj-properties "$vs_version" "$project_path" "${msbuild_arguments[@]}"
+}
+
+
 #
 # Main
 
-vdev_vm_file="$vdev_dir/$VM_FILE"
+vdev_vm_file="$VIRTUAL_DEV_WORKSPACE_DIR/$VM_FILE"
 dictionary-load "$vdev_vm_file" 'vm' 'guest_name'
 
 
@@ -189,6 +223,13 @@ dictionary-load "$vdev_vm_file" 'vm' 'guest_name'
 if [ $# \< 1 ]
 then
 	printf-vdev-error 'wrong number of arguments'
+	printf-message '%s' "$HELP_MESSAGE"
+	exit 1
+fi
+
+if ! validate-parameters "$@"
+then
+	printf-vdev-error 'bad arguments'
 	printf-message '%s' "$HELP_MESSAGE"
 	exit 1
 fi
@@ -212,12 +253,12 @@ fi
 
 # Paths file
 
-vdev_guest_paths_file="$vdev_dir/$GUEST_PATHS_FILE"
+vdev_guest_paths_file="$VIRTUAL_DEV_WORKSPACE_DIR/$GUEST_PATHS_FILE"
 
 detail/check-paths-file "$vdev_guest_paths_file"
 if [ $? == 2 ]
 then
-	printf-vdev-warning 'shared disk on "%s" for this project was changed. This may cause an error on running project. You may need to check paths in the solution.' "$guest_name"
+	printf-vdev-warning 'shared disk on "%s" for this workspace was changed. This may cause an error on running project. You may need to check paths in the solution.' "$guest_name"
 fi
 
 
@@ -239,7 +280,7 @@ fi
 project_path=$(project-path-from-parameters "$@")
 msbuild_arguments=($(msbuild-arguments-from-parameters "$@"))
 
-properties_dir="$vdev_dir/$VCXPROJ_PROPS_FILE"
+properties_dir="$VIRTUAL_DEV_WORKSPACE_DIR/$VCXPROJ_PROPS_FILE"
 mkdir -p "$properties_dir"
 if [ $? != 0 ]
 then
