dashed-script-names and dashed-function-names

diff --git a/detail/utils b/detail/utils
--- a/detail/utils
+++ b/detail/utils
@@ -1,52 +1,15 @@
 source detail/constants
 
+#
+# Module private
 
-has_terminal()
+has-terminal()
 {
 	tty -s
 }
 
 
-printf_message()
-{
-	printf "$@"
-	printf '\n'
-}
-
-
-printf_stderr()
-{
-	printf "$@" >&2
-}
-
-
-printf_vdev_error()
-{
-	local script_name="vdev-$(basename $0)"
-
-	if has_terminal
-	then
-		printf_stderr "$RED_TEXT"'%s error:'"$NEUTRAL_TEXT"' ' "$script_name"
-	else
-		printf_stderr '%s error: ' "$script_name"
-	fi
-
-	printf_stderr "$@"
-	printf_stderr '\n\n'
-}
-
-
-conf_add()
-{
-	local file=$1
-	local key=$2
-	local value=$3
-
-	printf '%s="%s"\n' "$key" "$value" >> "$file"
-}
-
-
-expand_dir_path()
+expand-dir-path()
 {
 	local path=$1
 
@@ -55,18 +18,50 @@ expand_dir_path()
 }
 
 
-expand_path()
+#
+# Module public
+
+printf-message()
+{
+	printf "$@"
+	printf '\n'
+}
+
+
+printf-stderr()
+{
+	printf "$@" >&2
+}
+
+
+printf-vdev-error()
+{
+	local script_name="vdev-$(basename $0)"
+
+	if has-terminal
+	then
+		printf-stderr "$RED_TEXT"'%s error:'"$NEUTRAL_TEXT"' ' "$script_name"
+	else
+		printf-stderr '%s error: ' "$script_name"
+	fi
+
+	printf-stderr "$@"
+	printf-stderr '\n\n'
+}
+
+
+expand-path()
 {
 	local path=$1
 
 	local dir=$(dirname "$path")
 	local base_name=$(basename "$path")
-	local absolute_dir_path=$(expand_dir_path "$dir")
+	local absolute_dir_path=$(expand-dir-path "$dir")
 	printf '%s\n' "$absolute_dir_path/$base_name"
 }
 
 
-dos2unix_path()
+dos2unix-path()
 {
 	local dos_path=$1
 
@@ -74,13 +69,13 @@ dos2unix_path()
 }
 
 
-trim_eoln()
+trim-eoln()
 {
 	sed -e $'s/\r$//g'
 }
 
 
-escape_backslashes()
+escape-backslashes()
 {
 	local dos_path=$1
 
@@ -97,25 +92,7 @@ unquote()
 }
 
 
-make_solution_cache_name()
-{
-	local path=$1
-
-	sed 's/\//\./g' <<< "$path"
-}
-
-
-make_solution_cache_path()
-{
-	local solution_path=$1
-	local out_dir=$2
-
-	local solution_cache_dir=$(make_solution_cache_name "$solution_path")
-	printf '%s\n' "$out_dir/$solution_cache_dir"
-}
-
-
-check_dir()
+check-dir()
 {
 	local path=$1
 
diff --git a/init b/init
--- a/init
+++ b/init
@@ -29,8 +29,8 @@ HELP_MESSAGE=\
 
 if [ $# -ne 3 ]
 then
-	printf_vdev_error 'wrong number of arguments'
-	printf_message '%s' "$HELP_MESSAGE"
+	printf-vdev-error 'wrong number of arguments'
+	printf-message '%s' "$HELP_MESSAGE"
 	exit 1
 fi
 
@@ -49,13 +49,13 @@ mkdir "$vdev_dir"
 
 vdev_vm_file="$vdev_dir/$VM_FILE"
 
-dictionary_insert "$vdev_vm_file" 'vm' "$vm"
-dictionary_insert "$vdev_vm_file" 'vm_manage' "$vm_manage"
-dictionary_insert "$vdev_vm_file" 'guest_name' "$guest_name"
-dictionary_insert "$vdev_vm_file" 'user' "$user"
-dictionary_insert "$vdev_vm_file" 'password' "$password"
+dictionary-insert "$vdev_vm_file" 'vm' "$vm"
+dictionary-insert "$vdev_vm_file" 'vm_manage' "$vm_manage"
+dictionary-insert "$vdev_vm_file" 'guest_name' "$guest_name"
+dictionary-insert "$vdev_vm_file" 'user' "$user"
+dictionary-insert "$vdev_vm_file" 'password' "$password"
 
-dictionary_load "$vdev_vm_file" 'vm' 'guest_name'
+dictionary-load "$vdev_vm_file" 'vm' 'guest_name'
 
 cp -Rn detail/guest "$vdev_dir/"
 
@@ -63,16 +63,16 @@ cp -Rn detail/guest "$vdev_dir/"
 # Checks
 
 vm_version=$(detail/"$vm"/version)
-if ! detail/check_vm_version "$vm_version" detail/"$vm"/required_versions
+if ! detail/check-vm-version "$vm_version" detail/"$vm"/required_versions
 then
-	printf_vdev_error 'current version of VirtualBox is not supported\nRequired versions are: %s' "$(cat detail/"$vm"/required_versions)"
+	printf-vdev-error 'current version of VirtualBox is not supported\nRequired versions are: %s' "$(cat detail/"$vm"/required_versions)"
 	exit 1
 fi
 
 
-if ! detail/"$vm"/vm_exists "$guest_name"
+if ! detail/"$vm"/vm-exists "$guest_name"
 then
-	printf_vdev_error '"%s" does not exist' "$guest_name"
+	printf-vdev-error '"%s" does not exist' "$guest_name"
 	exit 1
 fi
 
@@ -83,16 +83,16 @@ project_root="$working_dir"
 
 project_name=$(basename "$project_root")
 
-if detail/"$vm"/is_running "$guest_name"
+if detail/"$vm"/is-running "$guest_name"
 then
-	printf_vdev_error '"%s" is currently running, please shut it down' "$guest_name"
+	printf-vdev-error '"%s" is currently running, please shut it down' "$guest_name"
 	exit 1
 fi
 
-detail/"$vm"/shared_folder "$project_name" "$project_root"
+detail/"$vm"/shared-folder "$project_name" "$project_root"
 if [ $? != 0 ]
 then
-	printf_vdev_error 'failed to create shared folder on "%s"' "$vm"
+	printf-vdev-error 'failed to create shared folder on "%s"' "$vm"
 	exit 1
 fi
 
diff --git a/msbuild b/msbuild
--- a/msbuild
+++ b/msbuild
@@ -12,7 +12,7 @@ source detail/dictionary
 
 if [ ! -d "$vdev_dir" ]
 then
-	printf_vdev_error 'current path doesn'"'"'t have any virtual-dev configuration'
+	printf-vdev-error 'current path doesn'"'"'t have any virtual-dev configuration'
 	exit 1
 fi
 
@@ -45,7 +45,7 @@ vs_version=$1
 #
 # Funtions
 
-vs_version_for_parameters()
+vs-version-for-parameters()
 {
 	local first_parameter=$1
 
@@ -57,7 +57,7 @@ vs_version_for_parameters()
 
 	if ! [[ $first_parameter =~ .*\.sln ]]
 	then
-		local solution_path=$(detail/find_solution_for_project "$first_parameter")
+		local solution_path=$(detail/detect-solution-for-project "$first_parameter")
 	fi
 
 	if [ -z "$solution_path" ]
@@ -70,7 +70,7 @@ vs_version_for_parameters()
 		return 1
 	fi
 
-	detail/vs_version "$solution_path"
+	detail/vs-version "$solution_path"
 	if [ $? != 0 ]
 	then
 		return 1
@@ -78,7 +78,7 @@ vs_version_for_parameters()
 }
 
 
-msbuild_arguments_from_parameters()
+msbuild-arguments-from-parameters()
 {
 	local first_parameter=$1
 
@@ -95,20 +95,20 @@ msbuild_arguments_from_parameters()
 # Main
 
 vdev_vm_file="$vdev_dir/$VM_FILE"
-dictionary_load "$vdev_vm_file" 'vm' 'guest_name'
+dictionary-load "$vdev_vm_file" 'vm' 'guest_name'
 
 
 # Checks
 
-if ! detail/"$vm"/vm_exists "$guest_name"
+if ! detail/"$vm"/vm-exists "$guest_name"
 then
-	printf_vdev_error '"%s" does not exist' "$guest_name"
+	printf-vdev-error '"%s" does not exist' "$guest_name"
 	exit 1
 fi
 
-if ! detail/"$vm"/is_running "$guest_name"
+if ! detail/"$vm"/is-running "$guest_name"
 then
-	printf_vdev_error '"%s" is not running' "$guest_name"
+	printf-vdev-error '"%s" is not running' "$guest_name"
 	exit 1
 fi
 
@@ -117,8 +117,8 @@ fi
 
 if [ $# \< 1 ]
 then
-	printf_vdev_error 'too few arguments'
-	printf_message '%s' "$HELP_MESSAGE"
+	printf-vdev-error 'too few arguments'
+	printf-message '%s' "$HELP_MESSAGE"
 	exit 1
 fi
 
@@ -127,28 +127,29 @@ fi
 
 vdev_guest_paths_file="$vdev_dir/$GUEST_PATHS_FILE"
 
-detail/check_paths_file "$vdev_guest_paths_file"
-dictionary_load "$vdev_guest_paths_file" 'guest_root_dir' 'guest_msbuild_bat'
+detail/check-paths-file "$vdev_guest_paths_file"
+dictionary-load "$vdev_guest_paths_file" 'guest_root_dir' 'guest_msbuild_bat'
 
 
 # msbuild
 
-vs_version=$(vs_version_for_parameters "$@")
+vs_version=$(vs-version-for-parameters "$@")
+echo "VS version: $vs_version"
 if [ $? != 0 ]
 then
-	printf_vdev_error 'failed to detect Visual Studio version. Specify it explicitly.'
+	printf-vdev-error 'failed to detect Visual Studio version. Specify it explicitly.'
 	exit 1
 fi
 
-msbuild_arguments=($(msbuild_arguments_from_parameters "$@"))
+msbuild_arguments=($(msbuild-arguments-from-parameters "$@"))
 
 # passing arguments through environment variable, because "cmd.exe" will remove "=" character from arguments like "/property:configuration=Release"
 export virtual_dev_arguments="${msbuild_arguments[@]}"
-detail/"$vm"/execute "$guest_msbuild_bat" "$guest_root_dir" "$vs_version" | detail/error_format_mvs_to_gcc
+detail/"$vm"/execute "$guest_msbuild_bat" "$guest_root_dir" "$vs_version" | detail/error-format-mvs-to-gcc
 retval=${PIPESTATUS[0]}
 if [ $retval == 1 ]
 then
-	printf_vdev_error 'failed to execute build command.'
+	printf-vdev-error 'failed to execute build command.'
 	exit 1
 fi
 
diff --git a/run-vcxproj b/run-vcxproj
--- a/run-vcxproj
+++ b/run-vcxproj
@@ -12,7 +12,7 @@ source detail/dictionary
 
 if [ ! -d "$vdev_dir" ]
 then
-	printf_vdev_error 'current path doesn'"'"'t have any virtual-dev configuration'
+	printf-vdev-error 'current path doesn'"'"'t have any virtual-dev configuration'
 	exit 1
 fi
 
@@ -39,26 +39,7 @@ Notes:
 #
 # Functions
 
-check_paths_file()
-{
-	local paths_file=$1
-
-	local found_disk=$(detail/find_disk "$working_dir")
-	local guest_root_dir=$(dictionary_find "$paths_file" 'guest_root_dir')
-	if [ $? == 0 ] && [ "$found_disk" == "$guest_root_dir" ]
-	then
-		return
-	fi
-
-	local guest_vdev_guest_dir="$found_disk/.vdev/guest"
-
-	dictionary_insert "$paths_file" 'guest_root_dir' "$found_disk"
-	dictionary_insert "$paths_file" 'guest_msbuild_bat' "$guest_vdev_guest_dir/msbuild.bat"
-	dictionary_insert "$paths_file" 'guest_run_bat' "$guest_vdev_guest_dir/run.bat"
-}
-
-
-vs_version_for_parameters()
+vs-version-for-parameters()
 {
 	local first_parameter=$1
 
@@ -70,7 +51,7 @@ vs_version_for_parameters()
 
 	if ! [[ $first_parameter =~ .*\.sln ]]
 	then
-		local solution_path=$(detail/find_solution_for_project "$first_parameter")
+		local solution_path=$(detail/detect-solution-for-project "$first_parameter")
 	fi
 
 	if [ -z "$solution_path" ]
@@ -83,7 +64,7 @@ vs_version_for_parameters()
 		return 1
 	fi
 
-	detail/vs_version "$solution_path"
+	detail/vs-version "$solution_path"
 	if [ $? != 0 ]
 	then
 		return 1
@@ -91,7 +72,7 @@ vs_version_for_parameters()
 }
 
 
-project_path_from_parameters()
+project-path-from-parameters()
 {
 	local parameters=("$@")
 
@@ -105,7 +86,7 @@ project_path_from_parameters()
 }
 
 
-msbuild_arguments_from_parameters()
+msbuild-arguments-from-parameters()
 {
 	local first_parameter=$1
 
@@ -122,23 +103,23 @@ msbuild_arguments_from_parameters()
 # Main
 
 vdev_vm_file="$vdev_dir/$VM_FILE"
-dictionary_load "$vdev_vm_file" 'vm' 'guest_name'
+dictionary-load "$vdev_vm_file" 'vm' 'guest_name'
 
 vdev_guest_paths_file="$vdev_dir/$GUEST_PATHS_FILE"
-dictionary_load "$vdev_guest_paths_file" 'guest_root_dir' 'guest_run_bat'
+dictionary-load "$vdev_guest_paths_file" 'guest_root_dir' 'guest_run_bat'
 
 
 # Checks
 
-if ! detail/"$vm"/vm_exists "$guest_name"
+if ! detail/"$vm"/vm-exists "$guest_name"
 then
-	printf_vdev_error '"%s" does not exist' "$guest_name"
+	printf-vdev-error '"%s" does not exist' "$guest_name"
 	exit 1
 fi
 
-if ! detail/"$vm"/is_running "$guest_name"
+if ! detail/"$vm"/is-running "$guest_name"
 then
-	printf_vdev_error '"%s" is not running' "$guest_name"
+	printf-vdev-error '"%s" is not running' "$guest_name"
 	exit 1
 fi
 
@@ -147,8 +128,8 @@ fi
 
 if [ $# \< 1 ]
 then
-	printf_vdev_error 'wrong number of arguments'
-	printf_message '%s' "$HELP_MESSAGE"
+	printf-vdev-error 'wrong number of arguments'
+	printf-message '%s' "$HELP_MESSAGE"
 	exit 1
 fi
 
@@ -157,40 +138,40 @@ fi
 
 vdev_guest_paths_file="$vdev_dir/$GUEST_PATHS_FILE"
 
-detail/check_paths_file "$vdev_guest_paths_file"
-dictionary_load "$vdev_guest_paths_file" 'guest_root_dir' 'guest_msbuild_bat'
+detail/check-paths-file "$vdev_guest_paths_file"
+dictionary-load "$vdev_guest_paths_file" 'guest_root_dir' 'guest_msbuild_bat'
 
 
-vs_version=$(vs_version_for_parameters "$@")
+vs_version=$(vs-version-for-parameters "$@")
 if [ $? != 0 ]
 then
-	printf_vdev_error 'failed to detect Visual Studio version. Specify it explicitly'
+	printf-vdev-error 'failed to detect Visual Studio version. Specify it explicitly'
 	exit 1
 fi
 
-project_path=$(project_path_from_parameters "$@")
-msbuild_arguments=($(msbuild_arguments_from_parameters "$@"))
+project_path=$(project-path-from-parameters "$@")
+msbuild_arguments=($(msbuild-arguments-from-parameters "$@"))
 
-out_dir=$(detail/project_property "$vs_version" "$project_path" 'OutDir' "${msbuild_arguments[@]}")
+out_dir=$(detail/project-property "$vs_version" "$project_path" 'OutDir' "${msbuild_arguments[@]}")
 if [ $? != 0 ]
 then
-	printf_vdev_error 'failed to get project "OutDir" property'
+	printf-vdev-error 'failed to get project "OutDir" property'
 	exit 1
 fi
 
-out_dir=$(escape_backslashes "$out_dir")
+out_dir=$(escape-backslashes "$out_dir")
 
-name=$(detail/project_property "$vs_version" "$project_path" 'TargetName' "${msbuild_arguments[@]}")
+name=$(detail/project-property "$vs_version" "$project_path" 'TargetName' "${msbuild_arguments[@]}")
 if [ $? != 0 ]
 then
-	printf_vdev_error 'failed to get project "TargetName" property'
+	printf-vdev-error 'failed to get project "TargetName" property'
 	exit 1
 fi
 
-extension=$(detail/project_property "$vs_version" "$project_path" 'TargetExt' "${msbuild_arguments[@]}")
+extension=$(detail/project-property "$vs_version" "$project_path" 'TargetExt' "${msbuild_arguments[@]}")
 if [ $? != 0 ]
 then
-	printf_vdev_error 'failed to get project "TargetExt" property'
+	printf-vdev-error 'failed to get project "TargetExt" property'
 	exit 1
 fi
 
@@ -203,7 +184,7 @@ printf '\n' # if put newline in Windows then it can be swallowed ???
 
 if [ $retval == 1 ]
 then
-	printf_vdev_error 'failed to execute run command'
+	printf-vdev-error 'failed to execute run command'
 	exit 1
 fi
 
